### PR TITLE
Add PHP 8 to CI

### PR DESCRIPTION
**Pull request by lucaswerkmeister**
Bug: [T271109](https://phabricator.wikimedia.org/T271109)

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
PHPUnit too old

**Comment by itamargiv** [comment]
There seems to be an issue with php 7.2 now after the phpunit upgrade. Should we drop support?

**Comment by lucaswerkmeister** [comment]
No, since we still use PHP 7.2 in production.

**Comment by lucaswerkmeister** [comment]
I guess that’s why MediaWiki is still on PHPUnit 8 instead of 9. Let’s try downgrading a bit here.

**Comment by rosalieper** [comment]
LGTM

**Pull request merged**
